spring:
  datasource:
    # https://www.h2database.com/html/cheatSheet.html
    # 테스트db는 jdbc:h2:mem:test로 따로 설정해줄 수 있음
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true  # sout으로 로그 출력
        format_sql: true
        # 일대다 관계에서 컬렉션 페치 조인의 크기를 결정 (실무에서는 global 세팅을 주로 함)
        default_batch_fetch_size: 100


logging:
  level:
    org.hibernate.SQL: debug  # logger를 통해 로그 출력
#    org.hibernate.orm.jdbc.bind: trace  # 데이터의 타입을 로그로 출력. (스프링 3.0 + hibernate 6 기준)